# Generated by Django 3.0.6 on 2020-08-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
